# Generated by Django 3.1 on 2020-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200825_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='mypage',
            name='sex',
            field=models.BooleanField(choices=[(1, '남'), (2, '여')], default=1),
        ),
    ]
