# Generated by Django 3.1 on 2020-08-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200825_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='sex',
        ),
    ]
