# Generated by Django 3.1 on 2020-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200828_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='관심장소'),
        ),
    ]
