# Generated by Django 2.0.2 on 2020-08-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20200825_2155'),
        ('mapfunction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplace',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='myplace',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='myplace',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myplace',
            name='place',
        ),
        migrations.RemoveField(
            model_name='myplace',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='myplace',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Post'),
        ),
    ]
