# Generated by Django 3.1 on 2020-08-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('camp_type', models.CharField(choices=[('백패킹', '백패킹'), ('차박', '차박'), ('오토캠핑', '오토캠핑')], max_length=20, verbose_name='캠프 타입')),
                ('desc', models.TextField(verbose_name='내용')),
                ('position_latitude', models.FloatField(blank=True, default=None, null=True, verbose_name='위도')),
                ('position_longitude', models.FloatField(blank=True, default=None, null=True, verbose_name='경도')),
                ('address', models.CharField(default='', max_length=200, verbose_name='주소')),
                ('facility_toilet', models.BooleanField(default=False, verbose_name='화장실')),
                ('facility_showerroom', models.BooleanField(default=False, verbose_name='샤워실')),
                ('facility_cookroom', models.BooleanField(default=False, verbose_name='취사장')),
                ('facility_store', models.BooleanField(default=False, verbose_name='매점')),
                ('facility_electric', models.BooleanField(default=False, verbose_name='전기시설')),
                ('facility_water_sewage', models.BooleanField(default=False, verbose_name='상하수시설')),
                ('facility_fire', models.BooleanField(default=False, verbose_name='화재관련시설')),
                ('capacity', models.FloatField(blank=True, default=None, null=True, verbose_name='야영 가능한 사이트 수')),
                ('price_min', models.FloatField(blank=True, default=None, null=True, verbose_name='최소이용가격')),
                ('price_max', models.FloatField(blank=True, default=None, null=True, verbose_name='최대이용가격')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='처음작성시각')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, verbose_name='댓글')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='liked_com', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
