# Generated by Django 2.0.2 on 2020-08-03 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 16, 5, 31, 830540, tzinfo=utc), verbose_name='작성시간'),
        ),
    ]
