# Generated by Django 2.0.2 on 2020-08-04 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='내용')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간'),
        ),
    ]
