# Generated by Django 2.0.2 on 2020-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='내용'),
        ),
    ]
