# Generated by Django 2.0.2 on 2020-08-11 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_auto_20200808_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='liked_com', to=settings.AUTH_USER_MODEL),
        ),
    ]
