# Generated by Django 2.0.2 on 2020-08-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='https://runchi.dev'),
            preserve_default=False,
        ),
    ]
