# Generated by Django 2.0.2 on 2020-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='댓글'),
        ),
    ]
