# Generated by Django 3.1 on 2020-08-23 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20200815_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='camp_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_cookroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_showerroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facility_water_sewage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='position_latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='position_longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막수정시각'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='처음작성시각'),
        ),
    ]
