# Generated by Django 3.1 on 2020-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_remove_post_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='post',
            name='camp_type',
            field=models.CharField(default='', max_length=20, verbose_name='캠프 타입'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capacity',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='야영 가능한 사이트 수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_cookroom',
            field=models.BooleanField(default=False, verbose_name='취사장'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_electric',
            field=models.BooleanField(default=False, verbose_name='전기시설'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_fire',
            field=models.BooleanField(default=False, verbose_name='화재관련시설'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_showerroom',
            field=models.BooleanField(default=False, verbose_name='샤워실'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_store',
            field=models.BooleanField(default=False, verbose_name='매점'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_toilet',
            field=models.BooleanField(default=False, verbose_name='화장실'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facility_water_sewage',
            field=models.BooleanField(default=False, verbose_name='상하수시설'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position_latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position_longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='최대이용가격'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='최소이용가격'),
        ),
    ]
