# Generated by Django 3.1 on 2020-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20200825_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='camp_type',
            field=models.CharField(choices=[('백패킹', 'back'), ('차박', 'car'), ('오토캠핑', 'auto')], max_length=20, verbose_name='캠프 타입'),
        ),
    ]
